### ISSUE TITLE
Unable to use.

### ISSUE THREAD

**Issue by Lixiao-bai** [I3-Laboratory/Branch2Skeleton#2]
I tried to import my point cloud data into the software to extract the skeleton, and followed ：
The ASCII encoded .ply format file.
The file path does not contain Chinese characters.
The size of the branch point cloud is about 17k, which is less than 20k points.
The branch point cloud is clear, and its shape is radial (It's a pear tree just looked like the dome tree. )
However, when I select the .ply file that I want to import, the application interface crashes, causing me to be unable to use it.

**Comment by PPPengxinyu** [comment]
Please open your .ply file in text format, modify the header of file to the format of the sample .ply file provided, and then try again.

**Comment by Lixiao-bai** [comment]
It works, thanks a lot!!!
